# Assignement Practice for numpy


In [2]:
import numpy as np

In [5]:
arr = np.array(range(10,51,10))
arr

array([10, 20, 30, 40, 50])

In [7]:
arr_2 = np.array([range(1,3),range(3,5)])
arr_2

array([[1, 2],
       [3, 4]])

In [8]:
arr_3 = np.array([[range(1,3),range(3,5)]])
arr_3

array([[[1, 2],
        [3, 4]]])

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.full((4,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [23]:
x = np.array([range(5,16,5),range(20,31,5),range(35,46,5)])
x

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
# shape of array
np.shape(x)

(3, 3)

In [25]:
# total size of array
np.size(x) 

9

In [26]:
# dimension of array
np.ndim(x) 

2

In [28]:
# data type of array
x.dtype

dtype('int64')

In [31]:
float_arr = np.linspace(1,5,15)
float_arr

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [36]:
float_arr.dtype

dtype('float64')

In [32]:
bool_arr = np.array([True,False])
bool_arr

array([ True, False])

In [37]:
bool_arr.dtype

dtype('bool')

In [41]:
test = np.eye(3)
test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
test.dtype

dtype('float64')

In [44]:
str_arr = np.array(['a','b'])
str_arr


array(['a', 'b'], dtype='<U1')

In [45]:
str_arr.dtype

dtype('<U1')

In [46]:
a = np.array([5,10,15])
b = np.array([2,4,6])

In [47]:
a + b

array([ 7, 14, 21])

In [48]:
a - b

array([3, 6, 9])

In [49]:
a / b

array([2.5, 2.5, 2.5])

In [50]:
a * b

array([10, 40, 90])

In [52]:
a = np.array([10,20,30])
a

array([10, 20, 30])

In [53]:
a + 10

array([20, 30, 40])

In [54]:
a - 5

array([ 5, 15, 25])

In [55]:
a * 2

array([20, 40, 60])

In [56]:
a / 7

array([1.42857143, 2.85714286, 4.28571429])

In [59]:
full_arr = np.full((4,5),8)
full_arr

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [60]:
np.shape(full_arr)

(4, 5)

In [61]:
np.size(full_arr)

20

In [62]:
np.ndim(full_arr)

2

In [63]:
full_arr.dtype

dtype('int64')

In [64]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
y = np.array([1,2,3])
y * 5

array([ 5, 10, 15])

In [67]:
a = np.full((2,2),7)
a.ndim

2

In [73]:
t = np.full((4,4),100)
t

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [72]:
np.ndim(t)

2

In [74]:
np.shape(t)

(4, 4)

In [75]:
np.size(t)

16

In [76]:
t.dtype

dtype('int64')

In [77]:
ar = np.array([range(3,6),range(6,9)])
ar

array([[3, 4, 5],
       [6, 7, 8]])

In [78]:
ar *25

array([[ 75, 100, 125],
       [150, 175, 200]])

In [82]:
r = np.array(range(10,41,10))
r

array([10, 20, 30, 40])

In [83]:
m = np.array(range(1,5))
m

array([1, 2, 3, 4])

In [84]:
r + m

array([11, 22, 33, 44])

In [86]:
r - m

array([ 9, 18, 27, 36])

In [87]:
r* m

array([ 10,  40,  90, 160])

In [88]:
r /m

array([10., 10., 10., 10.])

In [89]:
r % m

array([0, 0, 0, 0])

In [90]:
np.zeros((5,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])