Numpyy leaarning


In [1]:
import numpy as np


np.array([1,3,5,7,9])


array([1, 3, 5, 7, 9])

In [3]:
nums=tuple(range(1,5))
np.array(nums)

array([1, 2, 3, 4])

In [4]:
num=set(range(1,5))
np.array(num)

array({1, 2, 3, 4}, dtype=object)

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((2,5),62)

array([[62, 62, 62, 62, 62],
       [62, 62, 62, 62, 62]])

In [10]:
np.arange(-10,10,1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.zeros((3,4))



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#creating 2D Array
x = list(range(1,5))
y = list(range(5,9))


np.array([x,y])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
ex_1 = np.arange(4,13)
ex_1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# np.ndim() this return the dimension  of an array

In [18]:
ex_2 = np.array([range(1,10),range(2,11),range(3,12)])
print(ex_2)
np.ndim(ex_2)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]]


2

In [11]:
np.ndim(ex_1)

1

In [13]:
# np.shapes() returns  row and col
np.shape(ex_2)

(3, 9)

In [14]:
np.shape(ex_1)

(9,)

In [ ]:
# np.size() returns the total number of items in list

In [19]:
np.size(ex_1)

9

In [20]:
np.size(ex_2)

27

In [24]:
# dtype return the data type of array
ex_1.dtype

dtype('int64')

In [25]:
ex_2.dtype

dtype('int64')

In [31]:
ex = np.array(['a','b','c','d','e'])
ex.dtype

dtype('<U1')

<h2>Operations in Array</h2>

In [12]:
# scalar operations

arr = np.array([range(1,4),range(2,5),range(2,5)])
arr

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [ ]:
# scalar multiply ( *) will multiple all elements by it

In [35]:
arr * 5

array([[ 5, 10, 15, 20],
       [10, 15, 20, 25]])

In [ ]:
# scalar division (/) will divide all elements by it 

In [36]:
arr / 5

array([[0.2, 0.4, 0.6, 0.8],
       [0.4, 0.6, 0.8, 1. ]])

In [37]:
# scalar addition

In [38]:
arr + 5

array([[ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [39]:
# scalar subtraction
arr - 5

array([[-4, -3, -2, -1],
       [-3, -2, -1,  0]])

In [40]:
# scalar modular 
arr % 2


array([[1, 0, 1, 0],
       [0, 1, 0, 1]])

In [41]:
# scalar power
arr ** 2


array([[ 1,  4,  9, 16],
       [ 4,  9, 16, 25]])

In [ ]:
# arithmetic operations


In [8]:
arr1 = np.array([range(1,4),range(2,5),range(3,6)])
arr1


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [9]:
arr2 = np.array([range(4,7),range(5,8),range(6,9)])
arr2

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [10]:
arr1 + arr2

array([[ 5,  7,  9],
       [ 7,  9, 11],
       [ 9, 11, 13]])

In [13]:
arr + arr1

array([[2, 4, 6],
       [4, 6, 8],
       [5, 7, 9]])

In [16]:

arr1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [19]:
arr - arr1


array([[ 0,  0,  0],
       [ 0,  0,  0],
       [-1, -1, -1]])

In [18]:
arr 

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [22]:
arr1 / arr


array([[1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ],
       [1.5       , 1.33333333, 1.25      ]])

In [23]:
arr1 % arr

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [24]:
arr * arr1

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [ 6, 12, 20]])

In [47]:
x = np.array([[range(1,6),range(2,7),range(3,8),range(3,8)]])
x

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7]]])

In [48]:
np.shape(x)

(1, 4, 5)

In [34]:
np.ndim(x)

3

In [40]:
y = np.array(range(1,5))
y


array([1, 2, 3, 4])

In [41]:
np.ndim(y)

1

In [43]:
np.shape(y)

(4,)