In [42]:
import numpy as np

In [41]:
a = ['a','b','c','d','e']
b = ['f','g','h','i','j']
c = ['k','l','m','n','o']
d = ['p','q','r','s','t']

In [5]:
demo = np.array([a,b,c,d])
demo

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j'],
       ['k', 'l', 'm', 'n', 'o'],
       ['p', 'q', 'r', 's', 't']], dtype='<U1')

In [6]:
np.shape(demo)

(4, 5)

In [7]:
demo[1]

array(['f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [8]:
demo[:,0]

array(['a', 'f', 'k', 'p'], dtype='<U1')

In [10]:
demo[:,1:3]

array([['b', 'c'],
       ['g', 'h'],
       ['l', 'm'],
       ['q', 'r']], dtype='<U1')

In [12]:
demo[:,0:3]

array([['a', 'b', 'c'],
       ['f', 'g', 'h'],
       ['k', 'l', 'm'],
       ['p', 'q', 'r']], dtype='<U1')

In [14]:
demo[0:2,0:3]

array([['a', 'b', 'c'],
       ['f', 'g', 'h']], dtype='<U1')

In [15]:
x = ['a','b','c','d','e','m','n']
y = ['f','g','h','i','j','q','r']
z = ['k','l','m','n','o','s','t']
g = ['p','q','r','s','t','q','r']
h = ['p','q','r','s','t','h','i']
i = ['p','q','r','s','t','b','c']

In [18]:
array = np.array([x,y,z,g,h,i])
array

array([['a', 'b', 'c', 'd', 'e', 'm', 'n'],
       ['f', 'g', 'h', 'i', 'j', 'q', 'r'],
       ['k', 'l', 'm', 'n', 'o', 's', 't'],
       ['p', 'q', 'r', 's', 't', 'q', 'r'],
       ['p', 'q', 'r', 's', 't', 'h', 'i'],
       ['p', 'q', 'r', 's', 't', 'b', 'c']], dtype='<U1')

In [20]:
# select row from 1 to 3
array[1:3]

array([['f', 'g', 'h', 'i', 'j', 'q', 'r'],
       ['k', 'l', 'm', 'n', 'o', 's', 't']], dtype='<U1')

In [21]:
# select col from index 2 to 4
array[:,2:4]


array([['c', 'd'],
       ['h', 'i'],
       ['m', 'n'],
       ['r', 's'],
       ['r', 's'],
       ['r', 's']], dtype='<U1')

In [23]:
# select from row 1 to 3 and col 4 to 7
array[1:3,4:7]

array([['j', 'q', 'r'],
       ['o', 's', 't']], dtype='<U1')

maths operations

In [24]:
a2 =  np.array([range(1,5),range(2,6),range(3,7),range(4,8),range(5,9)])
a2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [25]:
np.sum(a2) # sum of all

np.int64(90)

In [27]:
np.sum(a2,axis=0) # sum of each col 

array([15, 20, 25, 30])

In [29]:
np.sum(a2,axis=1) # sum of each row

array([10, 14, 18, 22, 26])

In [31]:
np.mean(a2)

np.float64(4.5)

In [33]:
np.mean(a2,axis=0) # mean of col

array([3., 4., 5., 6.])

In [34]:
np.mean(a2,axis=1) # mean of row 

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [35]:
np.max(a2)

np.int64(8)

In [36]:
np.max(a2,axis=0) # max number's row

array([5, 6, 7, 8])

In [44]:
np.max(a2,axis=1) # max number col

array([4, 5, 6, 7, 8])

In [38]:
np.min(a2)

np.int64(1)

In [39]:
np.min(a2,axis=0)

array([1, 2, 3, 4])

In [43]:
np.min(a2,axis=1)

array([1, 2, 3, 4, 5])